name: Terraform
on:
  issue_comment:
    types:
      - 'created'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        name: 'Run Terraform'
